### PR TITLE
adding precision 8 for bitfields

### PR DESCRIPTION
**Pull request by alexa-corista**
Proposing to add precision 8 for the bitfileds.
It turns out that in addition to previously added boolean bitfields, there is also bitfields with one-byte (8bit) precision, essentially turning bitfields into byte-arrays.

### CODE REVIEW

**Comment by jamesmudd** [comment]
Currently the tests are failing based on a checkstyle error, run `gradlew check` locally to see. However i'm not sure what issue this is fixing. Bitfield datasets are boolean, they happen to be stored as a byte array in the file but that's an implementation detail of hdf5 that I would rather not expose through the jhdf unless there is a clear use case. Could you attach (or send me) an example file and some code you expect to work that displays the issue? The existing implementation reads bitfields that are stored as byte arrays internally, but that is handled. See the test file https://github.com/jamesmudd/jhdf/blob/master/jhdf/src/test/resources/hdf5/bitfield_datasets.hdf5 and associated test https://github.com/jamesmudd/jhdf/blob/master/jhdf/src/test/java/io/jhdf/dataset/BitfieldDatasetTest.java for examples

**Comment by alexa-corista** [comment]
I think this is a good valid point, thank you!

What would be the best DataType to store images (like PNG, JPEG or BMP) in
Attributes?

I think Large Attribute with Fixed 1-byte sized DataType shall be the most
proper, is that right?
I would also say "unsigned" but I am not quite easy about handling of
unsigned bytes in DatasetReader.java.
https://github.com/jamesmudd/jhdf/blob/ad8fa51fbc8a25d3c628a73e966f2bd5507b7dfe/jhdf/src/main/java/io/jhdf/dataset/DatasetReader.java#L280

**Comment by jamesmudd** [comment]
OK I think I understand you really want to store a byte array? Then by first thought would also be unsigned bytes unfortunately java doesn't have unsigned type so all the unsigned types are promoted. I think the best would be signed byte that should work. There is also the hdf5 opaque type this might be right for this case but currently jhdf doesn't support it.

**Comment by jamesmudd** [comment]
Another idea could be to add the ability to get the data buffer from contiguous datasets then you could use that however you wanted. Similar to the raw chunk success but for a contiguous dataset there is effectively only one chunk

**Comment by jamesmudd** [comment]
Been thinking about this a bit more, and think you can probably do what you want if a method to get the data buffer is added to `Attribute`. So something like `Attribute#getDataBuffer` which would return a `ByteBuffer` the implementation in `AttributeImpl` would just be `message.getDataBuffer()` then you can convert the buffer to a `byte[]` if needed or pass it to a image decoder.

**Comment by jamesmudd** [comment]
Going to close this as I think the issue being address has been resolved by #170 adding ability to get the `ByteBuffer`.

**Pull request closed without merging**
