### PR TITLE
Add superblock extension support

### PR DESCRIPTION
**Pull request by jamesmudd**

### CODE REVIEW

**Comment by hoggatt** [comment]
Hi @jamesmudd, do you know when the release that includes this functionality will be pushed out? Very excited to try this out so that hdf5 files can be read from Nujan-created files.

**Comment by jamesmudd** [comment]
@hoggatt thanks for the comment. Sorry I haven't made a release been busy, but as there are a few things merged that would be useful to release I will try to do it this week.

**Comment by jamesmudd** [comment]
@hoggatt released in v0.6.10

**Comment by hoggatt** [comment]
Thanks @jamesmudd! Really appreciate it.

**Pull request merged**
